=== Consul Configuration Store

The Consul Configuration Store extends the Vert.x Configuration Retriever and provides the
way to retrieve configuration from a https://www.consul.io[Consul].

==== Using the Consul Configuration Store

To use the Consul Configuration Store, add the following dependency to the
_dependencies_ section of your build descriptor:

* Maven (in your `pom.xml`):

[source,xml,subs="+attributes"]
----
<dependency>
<<<<<<< HEAD:vertx-config-consul/src/main/asciidoc/groovy/consul-store.adoc
  <groupId>io.vertx</groupId>
  <artifactId>vertx-config-consul</artifactId>
  <version>3.5.1</version>
=======
  <groupId>${maven.groupId}</groupId>
  <artifactId>${maven.artifactId}</artifactId>
  <version>${maven.version}</version>
>>>>>>> Use plain adocs:vertx-config-consul/src/main/asciidoc/index.adoc
</dependency>
<dependency>
  <groupId>${maven.groupId}</groupId>
  <artifactId>vertx-config</artifactId>
<<<<<<< HEAD:vertx-config-consul/src/main/asciidoc/groovy/consul-store.adoc
  <version>3.5.1</version>
=======
  <version>${maven.version}</version>
>>>>>>> Use plain adocs:vertx-config-consul/src/main/asciidoc/index.adoc
</dependency>
----

* Gradle (in your `build.gradle` file):

[source,groovy,subs="+attributes"]
----
<<<<<<< HEAD:vertx-config-consul/src/main/asciidoc/groovy/consul-store.adoc
compile 'io.vertx:vertx-config:3.5.1'
compile 'io.vertx:vertx-config-consul:3.5.1'
=======
compile '${maven.groupId}:vertx-config:${maven.version}'
compile '${maven.groupId}:${maven.artifactId}:${maven.version}'
>>>>>>> Use plain adocs:vertx-config-consul/src/main/asciidoc/index.adoc
----

==== Configuring the store

Once added to your classpath or dependencies, you need to configure the
{@link io.vertx.config.ConfigRetriever} to use this store:

[source, $lang]
----
{@link examples.Examples#example1(io.vertx.core.Vertx)}
----

The store configuration is used to create an instance of
{@link io.vertx.ext.consul.ConsulClient}. Check the documentation of the Vert.x Consul Client
for further details. And this is the parameters specific to the Consul Configuration Store:

`prefix`:: A prefix that will not be taken into account when building the configuration tree. Defaults to empty.
`delimiter`:: Symbol that used to split keys in the Consul storage to obtain levels in the configuration tree. Defaults to "/".
