=== Hocon Configuration Format

The Hocon Configuration Format extends the Vert.x Configuration Retriever and provides the
support for the https://github.com/lightbend/config/blob/master/HOCON.md[HOCON] format.

It supports includes, json, properties, macros...

==== Using the Hocon Configuration Format

To use the Hocon Configuration Format, add the following dependency to the
_dependencies_ section of your build descriptor:

* Maven (in your `pom.xml`):

[source,xml,subs="+attributes"]
----
<dependency>
  <groupId>io.vertx</groupId>
  <artifactId>vertx-config-hocon</artifactId>
  <version>${maven.version}</version>
</dependency>
<dependency>
  <groupId>io.vertx</groupId>
  <artifactId>vertx-config</artifactId>
  <version>${maven.version}</version>
</dependency>
----

* Gradle (in your `build.gradle` file):

[source,groovy,subs="+attributes"]
----
compile 'io.vertx:vertx-config:${maven.version}'
compile 'io.vertx:vertx-config-hocon:${maven.version}'
----

==== Configuring the store to use HOCON

Once added to your classpath or dependencies, you need to configure the
{@link io.vertx.config.ConfigRetriever} to use this format:

[source, $lang]
----
{@link examples.ConfigHoconExamples#example1(io.vertx.core.Vertx)}
----

You just need to set `format` to `hocon`.

==== Override configuration using system environment variables

Hocon supports https://github.com/lightbend/config#optional-system-or-env-variable-overrides[system environment variable overrides] using keys with `CONFIG_FORCE_` prefix. You can use this feature by specifying `hocon.env.override` to `true` in the configuration:

[source, $lang]
----
{@link examples.ConfigHoconExamples#exampleWithEnvOverrides(io.vertx.core.Vertx)}
----
