=== Git Configuration Store

The Git Configuration Store is an extension to the Vert.x Configuration Retriever to
retrieve configuration from a Git repository.

==== Using the Git Configuration Store

To use the Git Configuration, add the following dependency to the
_dependencies_ section of your build descriptor:

* Maven (in your `pom.xml`):

[source,xml,subs="+attributes"]
----
<dependency>
<<<<<<< HEAD:vertx-config-git/src/main/asciidoc/groovy/git-store.adoc
  <groupId>io.vertx</groupId>
  <artifactId>vertx-config-git</artifactId>
  <version>3.5.1</version>
=======
  <groupId>${maven.groupId}</groupId>
  <artifactId>${maven.artifactId}</artifactId>
  <version>${maven.version}</version>
>>>>>>> Use plain adocs:vertx-config-git/src/main/asciidoc/index.adoc
</dependency>
<dependency>
  <groupId>${maven.groupId}</groupId>
  <artifactId>vertx-config</artifactId>
<<<<<<< HEAD:vertx-config-git/src/main/asciidoc/groovy/git-store.adoc
  <version>3.5.1</version>
=======
  <version>${maven.version}</version>
>>>>>>> Use plain adocs:vertx-config-git/src/main/asciidoc/index.adoc
</dependency>
----

* Gradle (in your `build.gradle` file):

[source,groovy,subs="+attributes"]
----
<<<<<<< HEAD:vertx-config-git/src/main/asciidoc/groovy/git-store.adoc
compile 'io.vertx:vertx-config:3.5.1'
compile 'io.vertx:vertx-config-git:3.5.1'
=======
compile '${maven.groupId}:vertx-config:${maven.version}'
compile '${maven.groupId}:${maven.artifactId}:${maven.version}'
>>>>>>> Use plain adocs:vertx-config-git/src/main/asciidoc/index.adoc
----

==== Configuring the store

Once added to your classpath or dependencies, you need to configure the
{@link io.vertx.config.ConfigRetriever} to use this store:

[source, $lang]
----
{@link examples.Examples#example1(io.vertx.core.Vertx)}
----

The configuration requires:

* the `url` of the repository
* the `path` where the repository is cloned (local directory)
* at least `fileset` indicating the set of files to read (same behavior as the
directory configuration store).

You can also configure the `branch` (`master` by default) to use and the name of the
`remote` repository (`origin` by default).

==== How does it works

If the local `path` does not exist, the configuration store clones the repository into
this directory. Then it reads the file matching the different file sets.

It the local `path` exist, it tried to update it (it switches branch if needed)). If the
update failed the configuration retrieval fails.

Periodically, the repositories is updated to check if the configuration has been updated.
