= Vert.x Configuration Service

The Vert.x Configuration service provides a way to configure your Vert.x application.

It:

* offer multiple configuration syntaxes (json, properties, yaml (extension), hocon
(extension)...
* offer multiple configuration stores (files, directories, http, git (extension), redis
(extension), system properties, environment properties)...
* let you define the processing order and overloading
* support runtime reconfiguration

== Concepts

The configuration service is structured around:

* a **configuration service** instantiated and used by the Vert.x application. It
configures a set of configuration store
* **configuration store** defines a location from where the configuration data is read
and and a syntax (json by default)

The configuration is retrieved as a JSON Object.

== Using the Vert.x Configuration Service

To use the Vert.x Configuration Service, add the following dependency to the
_dependencies_ section of your build descriptor:

* Maven (in your `pom.xml`):

[source,xml,subs="+attributes"]
----
<dependency>
  <groupId>me.escoffier.vertx</groupId>
  <artifactId>vertx-configuration</artifactId>
  <version>1.0.0-SNAPSHOT</version>
</dependency>
----

* Gradle (in your `build.gradle` file):

[source,groovy,subs="+attributes"]
----
compile 'me.escoffier.vertx:vertx-configuration:1.0.0-SNAPSHOT'
----

Once done, you first need to instantiate the `link:../../apidocs/io/vertx/ext/configuration/ConfigurationService.html[ConfigurationService]`:

[source]
----
ConfigurationService svc = ConfigurationService.create(vertx);
----

By default the Vert.x Configuration Service is configured with the following stores (in
this order):

* The Vert.x verticle `config()`
* The system properties
* The environment variables


You can configure your own stores:

[source]
----
ConfigurationStoreOptions httpStore = new ConfigurationStoreOptions()
    .setType("http")
    .setConfig(new JsonObject()
        .put("host", "localhost").put("port", 8080).put("path", "/conf"));

ConfigurationStoreOptions fileStore = new ConfigurationStoreOptions()
    .setType("file")
    .setConfig(new JsonObject().put("path", "my-config.json"));

ConfigurationStoreOptions sysPropsStore = new ConfigurationStoreOptions().setType("sys");


ConfigurationServiceOptions options = new ConfigurationServiceOptions()
    .addStore(httpStore).addStore(fileStore).addStore(sysPropsStore);

ConfigurationService svc = ConfigurationService.create(vertx, options);
----

More details about the overloading rules and available stores are available below.

Once you have the instance of the Vert.x Configuration Service, retrieve the configuration
as follows:

[source]
----
svc.getConfiguration(ar -> {
  if (ar.failed()) {
    // Failed to retrieve the configuration
  } else {
    JsonObject config = ar.result();
  }
});
----

=== Overloading rules

The declaration order of the configuration store is important as it defines the
overloading. For conflicting key, configuration stores arriving _last_ overloads the
value provided by the previous configuration stores. Let's take an example. We have 2
configuration stores:

* `A` provides `{a:value, b:1}`
* `B` provides `{a:value2, c:2}`

Declared in this order (A, B), the resulting configuration would be:
`{a:value2, b:1, c:2}`.

If you declare them in the reverse order (B, A), you would get: * `{a:value, b:1, c:2}`.

=== Available configuration stores

The Vert.x Configuration Service provides a set of configuration store and format.
Some more are available as extension and you can implement your own.

==== Structure of the configuration

Each declared data store must specify the `type`. It can also define the `format`. If
not set JSON is used.

Some configurations tore requires additional configuration (such a path...). This
configuration is passed as a Json Object using `link:../../apidocs/io/vertx/ext/configuration/ConfigurationStoreOptions.html#setConfig-io.vertx.core.json.JsonObject-[setConfig]`

==== File

This configuration store just read the configuration from a file. It supports all
supported formats.

[source, java]
----
ConfigurationStoreOptions file = new ConfigurationStoreOptions()
    .setType("file")
    .setFormat("properties")
    .setConfig(new JsonObject().put("path", "path-to-file.properties"));
----

The `path` configuration is required.

==== JSON

The JSON configuration store just serves the given JSON config as it is.

[source, java]
----
ConfigurationStoreOptions json = new ConfigurationStoreOptions()
    .setType("json")
    .setConfig(new JsonObject().put("key", "value"));
----

The only supported format for this configuration store is JSON.

==== Environment Variables

This configuration store maps environment variables to a Json Object contributed to
the global configuration.

[source, java]
----
ConfigurationStoreOptions json = new ConfigurationStoreOptions()
    .setType("env");
----

This configuration store does not support the `format` configuration.

==== System Properties

This configuration store maps system properties to a Json Object contributed to the
global configuration.

[source, java]
----
ConfigurationStoreOptions json = new ConfigurationStoreOptions()
    .setType("sys")
    .setConfig(new JsonObject().put("cache", "false"));
----

This configuration store does not support the `format` configuration.

You can configure the `cache` attribute (`true` by default) let you decide whether or
not it caches the system properties on the first access and does not reload them.

==== HTTP

This configuration stores retrieves the configuration from a HTTP location. It can use
any supported format.

[source, java]
----
ConfigurationStoreOptions http = new ConfigurationStoreOptions()
    .setType("http")
    .setConfig(new JsonObject()
        .put("host", "localhost")
        .put("port", 8080)
        .put("path", "/A"));
----

It creates a Vert.x HTTP Client with the store configuration (see next snippet). To
ease the configuration, you can also configure the `host`, `port` and `path` with the
`host`, `port` and `path`
properties.

[source, java]
----
ConfigurationStoreOptions http = new ConfigurationStoreOptions()
    .setType("http")
    .setConfig(new JsonObject()
        .put("defaultHost", "localhost")
        .put("defaultPort", 8080)
        .put("ssl", true)
        .put("path", "/A"));
----

==== Event Bus

This event bus configuration stores receives the configuration from the event bus. This
stores let you distribute your configuration among your local and distributed components.

[source, java]
----
ConfigurationStoreOptions eb = new ConfigurationStoreOptions()
    .setType("event-bus")
    .setConfig(new JsonObject()
        .put("address", "address-getting-the-conf")
    );
----

This configuration store supports any type of format.

==== Directory

This configuration store is similar to the `file` configuration store, but instead of
reading a single file, read several files from a directory.

This configuration store configuration requires:

* a `path` - the root directory in which files are located
* at least one `fileset` - an object to select the files

Each `fileset` contains:
* a `pattern` : a Ant style pattern to select files. The pattern is applied on the
relative path of the files location in the directory.
* an optional `format` indicating the format of the files (each fileset can use a
different format, BUT files in a fileset must share the same format).

[source, java]
----
ConfigurationStoreOptions dir = new ConfigurationStoreOptions()
    .setType("directory")
    .setConfig(new JsonObject().put("path", "config")
        .put("filesets", new JsonArray()
            .add(new JsonObject().put("pattern", "dir/*json"))
            .add(new JsonObject().put("pattern", "dir/*.properties")
                .put("format", "properties"))
        ));
----

=== Listening for configuration changes

The configuration service periodically retrieve the configuration and if the outcome
is different from the current one, your application can be reconfigured. By default the
configuration is reloaded every 5 seconds.

[source, java]
----
ConfigurationServiceOptions options = new ConfigurationServiceOptions()
    .setScanPeriod(2000)
    .addStore(store1)
    .addStore(store2);

ConfigurationService svc = ConfigurationService.create(Vertx.vertx(), options);
svc.getConfiguration(json -> {
  // Initial retrieval of the configuration
});

svc.listen(change -> {
  // Previous configuration
  JsonObject previous = change.getPreviousConfiguration();
  // New configuration
  JsonObject conf = change.getNewConfiguration();
});
----

=== Retrieving the last retrieved configuration

You can retrieved the last retrieved configuration without "waiting" to be retrieved
using:

[source, java]
----
JsonObject last = svc.getCachedConfiguration();
----

=== Reading configuration as a stream

The `link:../../apidocs/io/vertx/ext/configuration/ConfigurationService.html[ConfigurationService]` provide a way to access the stream of configuration.
It's a `link:../../apidocs/io/vertx/core/streams/ReadStream.html[ReadStream]` of `link:../../apidocs/io/vertx/core/json/JsonObject.html[JsonObject]`. By registering the right
set of handlers you are notified:

* when a new configuration is retrieved
* when an error occur while retrieving a configuration
* when the configuraiton service is close (the
`link:../../apidocs/io/vertx/ext/configuration/ConfigurationStream.html#endHandler-io.vertx.core.Handler-[endHandler]` is called).

[source, java]
----
ConfigurationServiceOptions options = new ConfigurationServiceOptions()
    .setScanPeriod(2000)
    .addStore(store1)
    .addStore(store2);

ConfigurationService svc = ConfigurationService.create(Vertx.vertx(), options);
svc.configurationStream()
    .endHandler(v -> {
      // Service closed
    })
    .exceptionHandler(t -> {
      // an error has been caught while retrieving the configuration
    })
    .handler(conf -> {
      // the configuration
    });
----

=== Extending the configuration service

You can extend the configuration by implementing:

* the `io.vertx.ext.configuration.spi.ConfigurationProcessor` SPI to add support for a
format
* the `io.vertx.ext.configuration.spi.ConfigurationStoreFactory` SPI to add support for
configuration store (place from where the configuration data is retrieved)