=== Zookeeper Configuration Store

The Zookeeper Configuration Store extends the Vert.x Configuration Retriever and provides the
way to retrieve configuration from a Zookeeper server. It uses Apache Curator as client.

==== Using the Zookeeper Configuration Store

To use the Redis Configuration Store, add the following dependency to the
_dependencies_ section of your build descriptor:

* Maven (in your `pom.xml`):

[source,xml,subs="+attributes"]
----
<dependency>
<<<<<<< HEAD:vertx-config-zookeeper/src/main/asciidoc/groovy/zookeeper-store.adoc
  <groupId>io.vertx</groupId>
  <artifactId>vertx-config-zookeeper</artifactId>
  <version>3.5.1</version>
=======
  <groupId>${maven.groupId}</groupId>
  <artifactId>${maven.artifactId}</artifactId>
  <version>${maven.version}</version>
>>>>>>> Use plain adocs:vertx-config-zookeeper/src/main/asciidoc/index.adoc
</dependency>
<dependency>
  <groupId>${maven.groupId}</groupId>
  <artifactId>vertx-config</artifactId>
<<<<<<< HEAD:vertx-config-zookeeper/src/main/asciidoc/groovy/zookeeper-store.adoc
  <version>3.5.1</version>
=======
  <version>${maven.version}</version>
>>>>>>> Use plain adocs:vertx-config-zookeeper/src/main/asciidoc/index.adoc
</dependency>
----

* Gradle (in your `build.gradle` file):

[source,groovy,subs="+attributes"]
----
<<<<<<< HEAD:vertx-config-zookeeper/src/main/asciidoc/groovy/zookeeper-store.adoc
compile 'io.vertx:vertx-config:3.5.1'
compile 'io.vertx:vertx-config-zookeeper:3.5.1'
=======
compile '${maven.groupId}:vertx-config:${maven.version}'
compile '${maven.groupId}:${maven.artifactId}:${maven.version}'
>>>>>>> Use plain adocs:vertx-config-zookeeper/src/main/asciidoc/index.adoc
----

==== Configuring the store

Once added to your classpath or dependencies, you need to configure the
{@link io.vertx.config.ConfigRetriever} to use this store:

[source, $lang]
----
{@link examples.Examples#example1(io.vertx.core.Vertx)}
----

The store configuration is used to configure the Apache Curator client and the _path_ of the Zookeeper node
containing the configuration. Notice that the format of the configuration can be JSON, or any supported format.

The configuration requires the `configuration` attribute indicating the connection _string_ of the Zookeeper
server, and the `path` attribute indicating the path of the node containing the configuration.

In addition you can configure:

* `maxRetries`: the number of connection attempt, 3 by default
* `baseSleepTimeBetweenRetries`: the amount of milliseconds to wait between retries (exponential backoff strategy).
1000 ms by default.
