=== AWS Secrets Manager Configuration Store

The AWS Secrets Manager Configuration Store extends the Vert.x Configuration Retriever and provides the way to retrieve configuration from AWS Secrets Manager.
It uses the AWS SDK as a client.

==== Using the AWS Secrets Manager Configuration Store

To use the AWS Secrets Manager Configuration Store, add the following dependency to the _dependencies_ section of your build descriptor:

* Maven (in your `pom.xml`):

[source,xml,subs="+attributes"]
----
<dependency>
  <groupId>io.vertx</groupId>
  <artifactId>vertx-config-aws-secrets-manager</artifactId>
  <version>${maven.version}</version>
</dependency>
<dependency>
  <groupId>io.vertx</groupId>
  <artifactId>vertx-config</artifactId>
  <version>${maven.version}</version>
</dependency>
----

* Gradle (in your `build.gradle` file):

[source,groovy,subs="+attributes"]
----
compile 'io.vertx:vertx-config:${maven.version}'
compile 'io.vertx:vertx-config-aws-secrets-manager:${maven.version}'
----

==== Configuring the store

Once added to your classpath or dependencies, you need to configure the {@link io.vertx.config.ConfigRetriever} to use this store:

[source,$lang]
----
{@link examples.ConfigAWSExamples#example1(io.vertx.core.Vertx)}
----

The store configuration is used to configure the AWS SDK client and the _secretName_ containing the configuration.
Notice that the format of the configuration can be PlainText JSON only.

You must also have the _AWS_ACCESS_KEY_ID_ & _AWS_SECRET_ACCESS_KEY_ environment variables set so AWS SDK can authenticate.
