= Kubernetes ConfigMap Store

The Kubernetes ConfigMap Store extends the Vert.x Configuration Service and provide the
support Kubernetes Config Map.

So, configuration is retrieved by reading the config map.

== Using the Kubernetes ConfigMap Store

To use the Kubernetes ConfigMap Store, add the following dependency to the
_dependencies_ section of your build descriptor:

* Maven (in your `pom.xml`):

[source,xml,subs="+attributes"]
----
<dependency>
<groupId>me.escoffier.vertx</groupId>
<artifactId>vertx-configuration-kubernetes-configmap</artifactId>
<version>1.0.0-SNAPSHOT</version>
</dependency>
<dependency>
<groupId>me.escoffier.vertx</groupId>
<artifactId>vertx-configuration</artifactId>
<version>1.0.0-SNAPSHOT</version>
</dependency>
----

* Gradle (in your `build.gradle` file):

[source,groovy,subs="+attributes"]
----
compile 'me.escoffier.vertx:vertx-configuration:1.0.0-SNAPSHOT'
compile 'me.escoffier.vertx:vertx-configuration-kubernetes-configmap:1.0.0-SNAPSHOT'
----

== Configuring the store

Once added to your classpath or dependencies, you need to configure the
`link:../../groovydoc/io/vertx/groovy/ext/configuration/ConfigurationService.html[ConfigurationService]` to use this store:

[source, groovy]
----
import io.vertx.groovy.ext.configuration.ConfigurationService
def store = [
  type:"configmap",
  config:[
    namespace:"my-project-namespace",
    name:"configmap-name"
  ]
]

def svc = ConfigurationService.create(vertx, [
  stores:[
    store
  ]
])

----

You need to configure the store to find the right configmap. this is done with:

* `namespace` - the project namespace, `default` by default
* `name` - the name of the config map

If the config map is composed by several element, you can use the `key` parameter to tell
which `key` is read

The application must have the permissions to read the config map.