=== Spring Config Server Store

The Spring Config Server Store extends the Vert.x Configuration Retriever and provides the
a way to retrieve configuration from a Spring Server.

==== Using the Spring Config Server Store

To use the Spring Config Server Store, add the following dependency to the
_dependencies_ section of your build descriptor:

* Maven (in your `pom.xml`):

[source,xml,subs="+attributes"]
----
<dependency>
<<<<<<< HEAD:vertx-config-spring-config-server/src/main/asciidoc/groovy/spring-store.adoc
  <groupId>io.vertx</groupId>
  <artifactId>vertx-config-spring-config-server</artifactId>
  <version>3.5.1</version>
=======
  <groupId>${maven.groupId}</groupId>
  <artifactId>${maven.artifactId}</artifactId>
  <version>${maven.version}</version>
>>>>>>> Use plain adocs:vertx-config-spring-config-server/src/main/asciidoc/index.adoc
</dependency>
<dependency>
  <groupId>${maven.groupId}</groupId>
  <artifactId>vertx-config</artifactId>
<<<<<<< HEAD:vertx-config-spring-config-server/src/main/asciidoc/groovy/spring-store.adoc
  <version>3.5.1</version>
=======
  <version>${maven.version}</version>
>>>>>>> Use plain adocs:vertx-config-spring-config-server/src/main/asciidoc/index.adoc
</dependency>
----

* Gradle (in your `build.gradle` file):

[source,groovy,subs="+attributes"]
----
<<<<<<< HEAD:vertx-config-spring-config-server/src/main/asciidoc/groovy/spring-store.adoc
compile 'io.vertx:vertx-config:3.5.1'
compile 'io.vertx:vertx-config-spring-config-server:3.5.1'
=======
compile '${maven.groupId}:vertx-config:${maven.version}'
compile '${maven.groupId}:${maven.artifactId}:${maven.version}'
>>>>>>> Use plain adocs:vertx-config-spring-config-server/src/main/asciidoc/index.adoc
----

==== Configuring the store

Once added to your classpath or dependencies, you need to configure the
{@link io.vertx.config.ConfigRetriever} to use this store:

[source, $lang]
----
{@link examples.Examples#example1(io.vertx.core.Vertx)}
----


Configurable attributes are:

* `url` - the `url` to retrieve the configuration (mandatory)
* `timeout` - the timeout (in milliseconds) to retrieve the configuration, 3000 by default
* `user` - the `user` (no authentication by default)
* `password` - the `password`
* `httpClientConfiguration` - the configuration of the underlying HTTP client
