= Redis Configuration Store

The Redis Configuration Store extends the Vert.x Configuration Retriever and provides the
way to retrieve configuration from a Redis server.

== Using the Redis Configuration Store

To use the Redis Configuration Store, add the following dependency to the
_dependencies_ section of your build descriptor:

* Maven (in your `pom.xml`):

[source,xml,subs="+attributes"]
----
<dependency>
  <groupId>io.vertx</groupId>
  <artifactId>vertx-configuration-redis-store</artifactId>
  <version>1.0.0-SNAPSHOT</version>
</dependency>
<dependency>
  <groupId>io.vertx</groupId>
  <artifactId>vertx-configuration</artifactId>
  <version>1.0.0-SNAPSHOT</version>
</dependency>
----

* Gradle (in your `build.gradle` file):

[source,groovy,subs="+attributes"]
----
compile 'io.vertx:vertx-configuration:1.0.0-SNAPSHOT'
compile 'io.vertx:vertx-configuration-redis-store:1.0.0-SNAPSHOT'
----

== Configuring the store

Once added to your classpath or dependencies, you need to configure the
`link:../../apidocs/io/vertx/ext/configuration/ConfigurationRetriever.html[ConfigurationRetriever]` to use this store:

[source, groovy]
----
import io.vertx.ext.configuration.ConfigurationRetriever
def store = [
  type:"redis",
  config:[
    host:"localhost",
    port:6379,
    key:"my-configuration"
  ]
]

def retriever = ConfigurationRetriever.create(vertx, [
  stores:[
    store
  ]
])

----

The store configuration is used to create an instance of
`link:../../apidocs/io/vertx/redis/RedisClient.html[RedisClient]`. check the documentation of the Vert.x Redis Client
for further details.

In addition, you can set the `key` instructing the store in which _field_ the configuration
is stored. `configuration` is used by default.

The created Redis client retrieves the configuration using the `HGETALL` configuration.