=== Redis Configuration Store

The Redis Configuration Store extends the Vert.x Configuration Retriever and provides the
way to retrieve configuration from a Redis server.

==== Using the Redis Configuration Store

To use the Redis Configuration Store, add the following dependency to the
_dependencies_ section of your build descriptor:

* Maven (in your `pom.xml`):

[source,xml,subs="+attributes"]
----
<dependency>
<<<<<<< HEAD:vertx-config-redis/src/main/asciidoc/groovy/redis-store.adoc
  <groupId>io.vertx</groupId>
  <artifactId>vertx-config-redis</artifactId>
  <version>3.5.1</version>
=======
  <groupId>${maven.groupId}</groupId>
  <artifactId>${maven.artifactId}</artifactId>
  <version>${maven.version}</version>
>>>>>>> Use plain adocs:vertx-config-redis/src/main/asciidoc/index.adoc
</dependency>
<dependency>
  <groupId>${maven.groupId}</groupId>
  <artifactId>vertx-config</artifactId>
<<<<<<< HEAD:vertx-config-redis/src/main/asciidoc/groovy/redis-store.adoc
  <version>3.5.1</version>
=======
  <version>${maven.version}</version>
>>>>>>> Use plain adocs:vertx-config-redis/src/main/asciidoc/index.adoc
</dependency>
----

* Gradle (in your `build.gradle` file):

[source,groovy,subs="+attributes"]
----
<<<<<<< HEAD:vertx-config-redis/src/main/asciidoc/groovy/redis-store.adoc
compile 'io.vertx:vertx-config:3.5.1'
compile 'io.vertx:vertx-config-redis:3.5.1'
=======
compile '${maven.groupId}:vertx-config:${maven.version}'
compile '${maven.groupId}:${maven.artifactId}:${maven.version}'
>>>>>>> Use plain adocs:vertx-config-redis/src/main/asciidoc/index.adoc
----

==== Configuring the store

Once added to your classpath or dependencies, you need to configure the
{@link io.vertx.config.ConfigRetriever} to use this store:

[source, $lang]
----
{@link examples.Examples#example1(io.vertx.core.Vertx)}
----

The store configuration is used to create an instance of
{@link io.vertx.redis.RedisClient}. check the documentation of the Vert.x Redis Client
for further details.

In addition, you can set the `key` instructing the store in which _field_ the configuration
is stored. `configuration` is used by default.

The created Redis client retrieves the configuration using the `HGETALL` configuration.
